essence/laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('institucional/{pagina?}', [
    'as'   => 'institucional',
    'uses' => 'InstitucionalController@index'
]);

Route::get('rede-credenciada', [
    'as'   => 'diferenciais',
    'uses' => 'DiferenciaisController@index'
]);

Route::get('servicos/{pagina?}', [
    'as'   => 'servicos',
    'uses' => 'ServicosController@index'
]);

Route::get('treinamento-a-distancia', [
    'as'   => 'treinamento',
    'uses' => 'TreinamentoController@index'
]);

Route::get('contato', [
    'as'   => 'contato',
    'uses' => 'ContatoController@index'
]);
Route::post('contato', [
    'as'   => 'contato.send',
    'uses' => 'ContatoController@send'
]);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('frase', 'Painel\FraseController');
    Route::resource('banners', 'Painel\BannersController');
    Route::resource('chamadas', 'Painel\ChamadasController');
    Route::resource('cabecalhos', 'Painel\CabecalhosController');
    Route::resource('institucional', 'Painel\InstitucionalController');
    Route::resource('rede-credenciada', 'Painel\DiferenciaisController');
    Route::resource('servicos', 'Painel\ServicosController');
    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('treinamento-a-distancia', 'Painel\TreinamentoController');
    Route::resource('treinamento-a-distancia.arquivos', 'Painel\TreinamentoArquivosController');
    Route::post('ajax/order', 'Painel\AjaxController@order');
});

essence/laravel/app/controllers/TreinamentoController.php
<?php

use \TreinamentoCategoria;

class TreinamentoController extends BaseController {

	public function index()
	{
        $categorias = TreinamentoCategoria::with('arquivos')->ordenados()->get();

		return $this->view('frontend.treinamento', compact('categorias'));
	}

}

essence/laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller;

class AjaxController extends Controller {

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

}

essence/laravel/app/controllers/painel/BannersController.php
<?php

namespace Painel;

use \Banner, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class BannersController extends BasePainelController {

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return $this->view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return $this->view('painel.banners.create');
    }

    public function store()
    {
        $input = Input::all();
        $rules = Banner::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', Banner::$imagem_config);
            Banner::create($input);
            Session::flash('sucesso', 'Banner criado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar banner.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $banner = Banner::findOrFail($id);

        return $this->view('painel.banners.edit', compact('banner'));
    }

    public function update($id)
    {
        $banner = Banner::findOrFail($id);
        $input  = Input::all();
        $rules  = Banner::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', Banner::$imagem_config);
            } else {
                unset($input['imagem']);
            }

            $banner->update($input);
            Session::flash('sucesso', 'Banner alterado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar banner.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Banner::destroy($id);
            Session::flash('sucesso', 'Banner removido com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover banner.']);

        }
    }

}

essence/laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = \ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));

            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

essence/laravel/app/controllers/painel/CabecalhosController.php
<?php

namespace Painel;

use \Cabecalho, \Input, \Validator, \Session, \Redirect, \CropImage;

class CabecalhosController extends BasePainelController {

    public function index()
    {
        $cabecalhos = Cabecalho::first();

        return $this->view('painel.cabecalhos.index', compact('cabecalhos'));
    }

    public function update($id)
    {
        $cabecalho = Cabecalho::findOrFail($id);
        $input     = Input::all();
        $rules     = Cabecalho::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            foreach ($input as $key => $value) {
                if (Input::hasFile($key)) {
                    $input[$key] = CropImage::make($key, Cabecalho::$imagem_config);
                } else {
                    unset($input[$key]);
                }
            }

            $cabecalho->update($input);
            Session::flash('sucesso', 'Imagens alteradas com sucesso.');

            return Redirect::route('painel.cabecalhos.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar imagens.'])
                ->withInput();

        }
    }

}

essence/laravel/app/controllers/painel/ChamadasController.php
<?php

namespace Painel;

use \Chamada, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class ChamadasController extends BasePainelController {

    public function index()
    {
        $chamadas = Chamada::ordenados()->get();

        return $this->view('painel.chamadas.index', compact('chamadas'));
    }

    public function edit($id)
    {
        $chamada = Chamada::findOrFail($id);

        return $this->view('painel.chamadas.edit', compact('chamada'));
    }

    public function update($id)
    {
        $chamada = Chamada::findOrFail($id);
        $input   = Input::all();
        $rules   = Chamada::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', Chamada::$imagem_config);
            } else {
                unset($input['imagem']);
            }

            $chamada->update($input);
            Session::flash('sucesso', 'Chamada alterada com sucesso.');

            return Redirect::route('painel.chamadas.index');

        } catch (\Exception $e) {

            dd($e);

            return Redirect::back()
                ->withErrors(['Erro ao alterar chamada.'])
                ->withInput();

        }
    }

}

essence/laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();
        $rules   = Contato::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

essence/laravel/app/controllers/painel/ContatosRecebidosController.php
<?php

namespace Painel;

use \ContatoRecebido, \Session, \Redirect, \View;

class ContatosRecebidosController extends BasePainelController {

    public function index()
    {
        $contatos_recebidos = ContatoRecebido::orderBy('created_at', 'desc')->get();

        return $this->view('painel.contatosrecebidos.index', compact('contatos_recebidos'));
    }

    public function show($id)
    {
        $contato = ContatoRecebido::findOrFail($id);
        $contato->update(['lido' => 'true']);

        $recebidos_count = ContatoRecebido::naoLidos()->count();
        View::share(compact('recebidos_count'));

        return $this->view('painel.contatosrecebidos.show', compact('contato'));
    }

    public function destroy($id)
    {
        try {

            ContatoRecebido::destroy($id);
            Session::flash('sucesso', 'Mensagem removida com sucesso.');

            return Redirect::route('painel.contato.recebidos.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover mensagem.']);

        }
    }

}

essence/laravel/app/controllers/painel/DiferenciaisController.php
<?php

namespace Painel;

use \Diferenciais, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class DiferenciaisController extends BasePainelController {

    public function index()
    {
        $diferenciais = Diferenciais::first();

        return $this->view('painel.diferenciais.edit', compact('diferenciais'));
    }

    public function update($id)
    {
        $diferenciais = Diferenciais::findOrFail($id);
        $input        = Input::all();
        $rules        = Diferenciais::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', Diferenciais::$imagem_config);
            } else {
                unset($input['imagem']);
            }

            $diferenciais->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.rede-credenciada.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

essence/laravel/app/controllers/painel/FraseController.php
<?php

namespace Painel;

use \Frase, \Input, \Session, \Redirect, \Validator;

class FraseController extends BasePainelController {

    public function index()
    {
        $frase = Frase::first();

        return $this->view('painel.frase.edit', compact('frase'));
    }

    public function update($id)
    {
        $frase = Frase::findOrFail($id);
        $input = Input::all();

        $validate = Validator::make($input, Frase::$rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $frase->update($input);
            Session::flash('sucesso', 'Frase alterada com sucesso.');

            return Redirect::route('painel.frase.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar frase.'])
                ->withInput();

        }
    }

}

essence/laravel/app/controllers/painel/HomeController.php
<?php

namespace Painel;

use \View, \Input, \Auth, \Session, \Redirect;

class HomeController extends BasePainelController {

    public function index()
    {
        return $this->view('painel.home');
    }

    public function login()
    {
        return $this->view('painel.login');
    }

    public function attempt()
    {
        $authvars = array(
            'username' => Input::get('username'),
            'password' => Input::get('password')
        );

        $lembrar = (Input::get('lembrar') == 'true') ? true : false;

        if (Auth::attempt($authvars, $lembrar)) {
            return Redirect::route('painel.home');
        } else {
            Session::flash('login_errors', true);
            return Redirect::route('painel.login')->withInput(Input::except('password'));
        }
    }

    public function logout()
    {
        Auth::logout();
        return Redirect::route('home');
    }

}

essence/laravel/app/controllers/painel/InstitucionalController.php
<?php

namespace Painel;

use \Institucional, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class InstitucionalController extends BasePainelController {

    public function index()
    {
        $institucional = Institucional::all();

        return $this->view('painel.institucional.index', compact('institucional'));
    }

    public function edit($id)
    {
        $institucional = Institucional::findOrFail($id);

        return $this->view('painel.institucional.edit', compact('institucional'));
    }

    public function update($id)
    {
        $institucional = Institucional::findOrFail($id);
        $input         = Input::all();
        $rules         = Institucional::$rules;

        $validate = Validator::make($input, $rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', Institucional::$imagem_config);
            } else {
                unset($input['imagem']);
            }

            $institucional->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.institucional.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

essence/laravel/app/views/painel/treinamento/_form.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ $error }}
    </div>
    @endforeach
@endif

@if(Session::has('sucesso'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ Session::get('sucesso') }}
    </div>
@endif

<div class="form-group">
    {{ Form::label('titulo', 'Título') }}
    {{ Form::text('titulo', null, ['class' => 'form-control']) }}
</div>

{{ Form::submit($submitText, ['class' => 'btn btn-success']) }}

<a href="{{ route('painel.treinamento-a-distancia.index') }}" class="btn btn-default btn-voltar">Voltar</a>

essence/laravel/app/views/painel/treinamento/create.blade.php
@section('content')

    <legend>
        <h2><small>Treinamento a Distância /</small> Adicionar Categoria</h2>
    </legend>

    {{ Form::open(['route' => 'painel.treinamento-a-distancia.store']) }}

        @include('painel.treinamento._form', ['submitText' => 'Inserir'])

    {{ Form::close() }}

@stop

essence/laravel/app/views/painel/treinamento/edit.blade.php
@section('content')

    <legend>
        <h2><small>Treinamento a Distância /</small> Editar Categoria</h2>
    </legend>

    {{ Form::model($categoria, [
        'route' => ['painel.treinamento-a-distancia.update', $categoria->id],
        'method' => 'patch'])
    }}

        @include('painel.treinamento._form', ['submitText' => 'Alterar'])

    {{ Form::close() }}

@stop

essence/laravel/app/views/painel/treinamento/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <legend>
        <h2>
            Treinamento a Distância
            <a href="{{ route('painel.treinamento-a-distancia.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Categoria</a>
        </h2>
    </legend>

    @if(count($categorias))
    <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="treinamento_categorias">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Categoria</th>
                <th>Arquivos</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($categorias as $categoria)

            <tr class="tr-row" id="id_{{ $categoria->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $categoria->titulo }}</td>
                <td>
                    <a href="{{ route('painel.treinamento-a-distancia.arquivos.index', $categoria->id ) }}" class="btn btn-default btn-sm pull-left">
                        <span class="glyphicon glyphicon-file" style="margin-right:10px;"></span>Gerenciar
                    </a>
                </td>
                <td class="crud-actions">
                    {{ Form::open(array('route' => array('painel.treinamento-a-distancia.destroy', $categoria->id), 'method' => 'delete')) }}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.treinamento-a-distancia.edit', $categoria->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhuma categoria cadastrada.</div>
    @endif

@stop